import React, { useEffect, useState } from "react";
import { Page, Table, Btn, Danger, Modal } from "../components/UI";
import { addresses, users } from "../api";
import { fmtDate } from "../utils/helpers";
import { canAdmin } from "../utils/adminPermissions";

const blank = { user: "", fullName: "", phone: "", province: "", district: "", ward: "", address: "", note: "", latitude: "", longitude: "", isDefault: false };
const getRows = (response) => { const data = response.data?.data ?? response.data; return Array.isArray(data) ? data : data?.data || []; };

export default function AddressesPage() {
  const [rows, setRows] = useState([]), [customers, setCustomers] = useState([]), [error, setError] = useState("");
  const [editing, setEditing] = useState(null), [formOpen, setFormOpen] = useState(false), [form, setForm] = useState(blank), [saving, setSaving] = useState(false);
  const canCreate = canAdmin("address.create"), canUpdate = canAdmin("address.update"), canDelete = canAdmin("address.delete");
  const load = async () => { setError(""); const [a, u] = await Promise.allSettled([addresses.list({ page: 1, limit: 100 }), users.list({ page: 1, limit: 100, role: "customer" })]); if (a.status === "fulfilled") setRows(getRows(a.value)); else setError(a.reason.response?.data?.message || a.reason.message); if (u.status === "fulfilled") setCustomers(getRows(u.value)); };
  useEffect(() => { load(); }, []);
  const open = (row) => { setError(""); setEditing(row || null); setFormOpen(true); setForm(row ? { ...blank, ...row, user: row.user?._id || row.user || "" } : { ...blank, user: customers[0]?._id || "" }); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { if (editing) await addresses.update(editing._id, form); else await addresses.create(form); setFormOpen(false); setEditing(null); await load(); } catch (e) { setError(e.response?.data?.message || e.message); } finally { setSaving(false); } };
  const remove = async (row) => { if (!window.confirm(`Xóa địa chỉ của ${row.fullName}?`)) return; try { await addresses.remove(row._id); await load(); } catch (e) { setError(e.response?.data?.message || e.message); } };
  const field = (key, label, required = true) => <label key={key}>{label}{key === "user" ? canAdmin("user.read") ? <select required value={form.user} onChange={e => setForm({ ...form, user: e.target.value })}><option value="">Chọn khách hàng</option>{customers.map(u => <option key={u._id} value={u._id}>{u.name} · {u.email}</option>)}{form.user && !customers.some(u => u._id === form.user) && <option value={form.user}>{editing?.user?.name || editing?.user?.email || "Khách hàng hiện tại"}</option>}</select> : <input value={editing?.user?.name || editing?.user?.email || "Tài khoản khách hiện tại"} readOnly /> : <input required={required} value={form[key] || ""} onChange={e => setForm({ ...form, [key]: e.target.value })} />}</label>;
  return <Page title="Địa chỉ giao hàng" actions={<><Btn onClick={load}>↻ Làm mới</Btn>{canCreate && <Btn className="primary" onClick={() => open(null)}>+ Thêm địa chỉ</Btn>}</>}>
    <div className="info-banner"><b>Quản lý địa chỉ khách hàng.</b> Chọn đúng tài khoản trước khi thêm; địa chỉ mặc định được khách dùng ở bước thanh toán. Chỉ xóa khi khách xác nhận địa chỉ không còn sử dụng.</div>
    {error && !formOpen && <div className="error">{error}</div>}
    <Table rows={rows} columns={[{key:'user',label:'Khách hàng',render:r=><div><b>{r.user?.name||'—'}</b><small>{r.user?.email||''}</small></div>},{key:'fullName',label:'Người nhận',render:r=><b>{r.fullName}</b>},{key:'phone',label:'SĐT'},{key:'address',label:'Địa chỉ',render:r=>[r.address,r.ward,r.district,r.province].filter(Boolean).join(', ')},{key:'isDefault',label:'Mặc định',render:r=>r.isDefault?<span className="status-pill approved">Mặc định</span>:'—'},{key:'createdAt',label:'Ngày',render:r=>fmtDate(r.createdAt)},{key:'actions',label:'Thao tác',render:r=><span className="actions">{canUpdate&&<Btn onClick={()=>open(r)}>Sửa</Btn>}{canDelete&&<Danger onClick={()=>remove(r)}>Xóa</Danger>}</span>}]}/>
    {formOpen && <Modal title={editing ? "Sửa địa chỉ" : "Thêm địa chỉ"} onClose={() => setFormOpen(false)}><form className="formgrid" onSubmit={save}>{error&&<div className="error full">{error}</div>}{field("user","Tài khoản khách hàng")}{field("fullName","Tên người nhận")}{field("phone","Số điện thoại")}{field("province","Tỉnh / thành phố")}{field("district","Quận / huyện")}{field("ward","Phường / xã")}{field("address","Địa chỉ cụ thể")}{field("note","Ghi chú",false)}<label>Vĩ độ<input type="number" step="any" value={form.latitude??""} onChange={e=>setForm({...form,latitude:e.target.value})}/></label><label>Kinh độ<input type="number" step="any" value={form.longitude??""} onChange={e=>setForm({...form,longitude:e.target.value})}/></label><label className="full"><span><input type="checkbox" checked={Boolean(form.isDefault)} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> Đặt làm địa chỉ mặc định</span></label><div className="full"><Btn type="button" onClick={()=>setFormOpen(false)}>Hủy</Btn> <Btn className="primary" disabled={saving}>{saving?"Đang lưu…":"Lưu địa chỉ"}</Btn></div></form></Modal>}
  </Page>;
}
