import React, { useEffect, useState } from "react";
import { Page, Table, Money, Btn, Danger, Modal } from "../components/UI";
import { carts, users, products, variants } from "../api";
import { canAdmin } from "../utils/adminPermissions";

const rowsFrom = (response) => { const data = response.data?.data ?? response.data; return Array.isArray(data) ? data : data?.data || []; };
const blankItem = { product: "", variant: "", quantity: 1, price: 0, attributesText: "{}" };

export default function CartsPage() {
  const [rows, setRows] = useState([]), [customers, setCustomers] = useState([]), [productRows, setProductRows] = useState([]), [variantRows, setVariantRows] = useState([]), [error, setError] = useState("");
  const [open, setOpen] = useState(false), [editing, setEditing] = useState(null), [form, setForm] = useState({ user: "", items: [] }), [saving, setSaving] = useState(false);
  const canCreate = canAdmin("cart.create"), canUpdate = canAdmin("cart.update"), canDelete = canAdmin("cart.delete");
  const load = async () => { setError(""); const results = await Promise.allSettled([carts.list({page:1,limit:100}), users.list({page:1,limit:100,role:"customer"}), products.list({page:1,limit:100}), variants.list({page:1,limit:100})]);
    if(results[0].status==="fulfilled")setRows(rowsFrom(results[0].value));else setError(results[0].reason.response?.data?.message||results[0].reason.message);
    if(results[1].status==="fulfilled")setCustomers(rowsFrom(results[1].value));if(results[2].status==="fulfilled")setProductRows(rowsFrom(results[2].value));if(results[3].status==="fulfilled")setVariantRows(rowsFrom(results[3].value));
  };
  useEffect(()=>{load()},[]);
  const showForm=(row)=>{setEditing(row||null);setForm(row?{user:row.user?._id||row.user||"",items:(row.items||[]).map(item=>({product:item.product?._id||item.product||"",variant:item.variant?._id||item.variant||"",quantity:item.quantity||1,price:item.price||0,attributesText:JSON.stringify(item.attributes||{},null,2)}))}:{user:"",items:[]});setError("");setOpen(true)};
  const save=async(event)=>{event.preventDefault();setSaving(true);setError("");try{const payload={user:form.user,items:form.items.map(item=>{const attributes=JSON.parse(item.attributesText||"{}");const{attributesText,...fields}=item;return{...fields,quantity:Number(item.quantity),price:Number(item.price),attributes}})};if(editing)await carts.update(editing._id,payload);else await carts.create(payload);setOpen(false);await load()}catch(e){setError(e instanceof SyntaxError?"Thuộc tính Variant phải là JSON hợp lệ.":e.response?.data?.message||e.message)}finally{setSaving(false)}};
  const remove=async(row)=>{if(!window.confirm(`Xóa giỏ hàng của ${row.user?.name||row.user?.email||"khách hàng này"}?`))return;try{await carts.remove(row._id);await load()}catch(e){setError(e.response?.data?.message||e.message)}};
  const updateItem=(index,patch)=>setForm(current=>({...current,items:current.items.map((item,i)=>i===index?{...item,...patch}:item)}));
  const count=row=>(row.items||[]).reduce((sum,item)=>sum+Number(item.quantity||0),0), value=row=>(row.items||[]).reduce((sum,item)=>sum+Number(item.price||0)*Number(item.quantity||0),0);
  return <Page title="Giỏ hàng khách" actions={<><Btn onClick={load}>↻ Làm mới</Btn>{canCreate&&<Btn className="primary" onClick={()=>showForm(null)}>+ Tạo giỏ hàng</Btn>}</>}>
    <div className="info-banner"><b>Quản lý giỏ hàng và các dòng sản phẩm.</b> Mỗi khách chỉ có một giỏ. Giá nhập theo từng Variant; thay đổi giỏ sẽ ảnh hưởng nội dung khách nhìn thấy ở bước mua hàng.</div>
    {error&&!open&&<div className="error">{error}</div>}
    <Table rows={rows} columns={[{key:"user",label:"Khách hàng",render:row=><div><b>{row.user?.name||"—"}</b><small>{row.user?.email||""}</small></div>},{key:"items",label:"Sản phẩm",render:row=><div className="cart-items-mini">{(row.items||[]).slice(0,3).map((item,i)=><span key={i}>{item.product?.name||"Sản phẩm"} × {item.quantity}</span>)}{(row.items||[]).length>3&&<span>+{row.items.length-3} sản phẩm</span>}</div>},{key:"count",label:"Số lượng",render:row=><b>{count(row)}</b>},{key:"value",label:"Giá trị tạm tính",render:row=><b><Money v={value(row)}/></b>},{key:"actions",label:"Thao tác",render:row=><span className="actions">{canUpdate&&<Btn onClick={()=>showForm(row)}>Sửa</Btn>}{canDelete&&<Danger onClick={()=>remove(row)}>Xóa</Danger>}</span>}]}/>
    {open&&<Modal title={editing?"Sửa giỏ hàng":"Tạo giỏ hàng"} onClose={()=>setOpen(false)}><form className="formgrid" onSubmit={save}>{error&&<div className="error full">{error}</div>}<label className="full">Tài khoản khách hàng<select required value={form.user} onChange={e=>setForm({...form,user:e.target.value})}><option value="">Chọn khách</option>{customers.map(user=><option key={user._id} value={user._id}>{user.name} · {user.email}</option>)}{editing?.user?._id&&!customers.some(user=>user._id===form.user)&&<option value={form.user}>{editing.user.name||form.user}</option>}</select><small>Một khách hàng chỉ được có một giỏ hàng.</small></label><div className="full"><h3>Sản phẩm trong giỏ</h3>{form.items.map((item,index)=><div className="panel" key={index}><div className="formgrid"><label>Sản phẩm<select required value={item.product} onChange={e=>updateItem(index,{product:e.target.value})}><option value="">Chọn sản phẩm</option>{productRows.map(product=><option key={product._id} value={product._id}>{product.name}</option>)}</select></label><label>Variant / SKU<select required value={item.variant} onChange={e=>updateItem(index,{variant:e.target.value})}><option value="">Chọn Variant</option>{variantRows.map(variant=><option key={variant._id} value={variant._id}>{variant.sku||variant._id} · {variant.product?.name||"Variant"}</option>)}</select></label><label>Số lượng<input type="number" min="1" required value={item.quantity} onChange={e=>updateItem(index,{quantity:e.target.value})}/></label><label>Giá một sản phẩm<input type="number" min="0" required value={item.price} onChange={e=>updateItem(index,{price:e.target.value})}/></label><label className="full">Thuộc tính Variant (JSON)<textarea rows="2" value={item.attributesText||"{}"} onChange={e=>updateItem(index,{attributesText:e.target.value})}/></label></div><Danger type="button" onClick={()=>setForm(current=>({...current,items:current.items.filter((_,i)=>i!==index)}))}>Xóa dòng sản phẩm</Danger></div>)}<Btn type="button" onClick={()=>setForm(current=>({...current,items:[...current.items,{...blankItem}]}))}>+ Thêm dòng sản phẩm</Btn></div><div className="full"><Btn type="button" onClick={()=>setOpen(false)}>Hủy</Btn> <Btn className="primary" disabled={saving}>{saving?"Đang lưu…":"Lưu giỏ hàng"}</Btn></div></form></Modal>}
  </Page>;
}
