import React, { useEffect, useState } from "react";
import { Page, Table, Btn, Danger, Modal } from "../components/UI";
import { notifications, users } from "../api";
import { fmtDate } from "../utils/helpers";
import { canAdmin } from "../utils/adminPermissions";

const types = { order: "Đơn hàng", payment: "Thanh toán", promotion: "Khuyến mãi", system: "Hệ thống", review: "Đánh giá" };
const blank = { user: "", type: "system", title: "", message: "", isRead: false, dataText: "{}" };
const getRows = (response) => { const data = response.data?.data ?? response.data; return Array.isArray(data) ? data : data?.data || []; };

export default function NotificationsPage() {
  const [rows, setRows] = useState([]), [customers, setCustomers] = useState([]), [filter, setFilter] = useState(""), [error, setError] = useState("");
  const [open, setOpen] = useState(false), [editing, setEditing] = useState(null), [form, setForm] = useState(blank), [saving, setSaving] = useState(false);
  const canCreate = canAdmin("notification.create"), canUpdate = canAdmin("notification.update"), canDelete = canAdmin("notification.delete");
  const load = async () => { setError(""); const [n, u] = await Promise.allSettled([notifications.list({ page: 1, limit: 100, ...(filter ? { isRead: filter } : {}) }), users.list({ page: 1, limit: 100, role: "customer" })]); if (n.status === "fulfilled") setRows(getRows(n.value)); else setError(n.reason.response?.data?.message || n.reason.message); if (u.status === "fulfilled") setCustomers(getRows(u.value)); };
  useEffect(() => { load(); }, [filter]);
  const showForm = (row) => { setEditing(row || null); setForm(row ? { user: row.user?._id || row.user || "", type: row.type, title: row.title || "", message: row.message || "", isRead: Boolean(row.isRead), dataText: JSON.stringify(row.data || {}, null, 2) } : { ...blank, user: customers[0]?._id || "" }); setError(""); setOpen(true); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const payload = { ...form, data: JSON.parse(form.dataText || "{}") }; delete payload.dataText; if (editing && payload.isRead && !editing.isRead) payload.readAt = new Date().toISOString(); if (editing && !payload.isRead) payload.readAt = null; if (editing) await notifications.update(editing._id, payload); else await notifications.create(payload); setOpen(false); await load(); } catch (e) { setError(e instanceof SyntaxError ? "Dữ liệu bổ sung phải là JSON hợp lệ." : e.response?.data?.message || e.message); } finally { setSaving(false); } };
  const remove = async (row) => { if (!window.confirm(`Xóa thông báo “${row.title}”?`)) return; try { await notifications.remove(row._id); await load(); } catch (e) { setError(e.response?.data?.message || e.message); } };
  const read = async (row) => { try { await notifications.update(row._id, { isRead: true, readAt: new Date().toISOString() }); await load(); } catch (e) { setError(e.response?.data?.message || e.message); } };
  return <Page title="Thông báo khách hàng" actions={<><Btn onClick={load}>↻ Làm mới</Btn>{canCreate && <Btn className="primary" onClick={() => showForm(null)}>+ Tạo thông báo</Btn>}</>}>
    <div className="info-banner"><b>Thông báo được gửi đến tài khoản đã chọn.</b> Kiểm tra đúng người nhận và nội dung trước khi lưu. Trạng thái đã đọc do khách hàng cập nhật; thao tác quản trị chỉ hỗ trợ đánh dấu đã đọc.</div>
    <div className="toolbar"><select value={filter} onChange={e => setFilter(e.target.value)}><option value="">Tất cả trạng thái</option><option value="false">Chưa đọc</option><option value="true">Đã đọc</option></select></div>
    {error && !open && <div className="error">{error}</div>}
    <Table rows={rows} columns={[{key:'title',label:'Thông báo',render:r=><div className={r.isRead?'':'notification-unread'}><b>{r.title}</b><small>{r.message}</small></div>},{key:'user',label:'Người nhận',render:r=><div><b>{r.user?.name||'—'}</b><small>{r.user?.email||''}</small></div>},{key:'type',label:'Loại',render:r=><span className="soft-badge">{types[r.type]||r.type}</span>},{key:'isRead',label:'Trạng thái',render:r=>r.isRead?'Đã đọc':<span className="status-pill pending">Chưa đọc</span>},{key:'createdAt',label:'Ngày',render:r=>fmtDate(r.createdAt)},{key:'actions',label:'Thao tác',render:r=><span className="actions">{!r.isRead&&canUpdate&&<Btn onClick={()=>read(r)}>Đã đọc</Btn>}{canUpdate&&<Btn onClick={()=>showForm(r)}>Sửa</Btn>}{canDelete&&<Danger onClick={()=>remove(r)}>Xóa</Danger>}</span>}]}/>
    {open && <Modal title={editing ? "Sửa thông báo" : "Tạo thông báo"} onClose={() => setOpen(false)}><form className="formgrid" onSubmit={save}>{error&&<div className="error full">{error}</div>}<label className="full">Người nhận{canAdmin("user.read")?<select required value={form.user} onChange={e=>setForm({...form,user:e.target.value})}><option value="">Chọn khách hàng</option>{customers.map(u=><option key={u._id} value={u._id}>{u.name} · {u.email}</option>)}{form.user&&!customers.some(u=>u._id===form.user)&&<option value={form.user}>{editing?.user?.name||editing?.user?.email||"Khách hàng hiện tại"}</option>}</select>:<input value={editing?.user?.name||editing?.user?.email||"Tài khoản khách hiện tại"} readOnly/>}<small>Thông báo sẽ hiển thị trong tài khoản của người này.</small></label><label>Loại thông báo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{Object.entries(types).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Tiêu đề<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="full">Nội dung<textarea required rows="4" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><label className="full">Dữ liệu bổ sung (JSON)<textarea rows="3" value={form.dataText} onChange={e=>setForm({...form,dataText:e.target.value})}/></label>{editing&&<label className="full"><span><input type="checkbox" checked={form.isRead} onChange={e=>setForm({...form,isRead:e.target.checked})}/> Đã đọc</span></label>}<div className="full"><Btn type="button" onClick={()=>setOpen(false)}>Hủy</Btn> <Btn className="primary" disabled={saving}>{saving?"Đang lưu…":"Lưu thông báo"}</Btn></div></form></Modal>}
  </Page>;
}
