import React,{useEffect,useMemo,useState}from"react";
import{Link}from"react-router-dom";
import{Page,Table,Money,Btn,Danger,Modal}from"../components/UI";
import{orderItems,orders,products,variants}from"../api";
import{canAdmin}from"../utils/adminPermissions";
const getRows=response=>{const data=response.data?.data??response.data;return Array.isArray(data)?data:data?.data||[]};
const blank={order:"",product:"",variant:"",productName:"",variantName:"",sku:"",image:"",price:0,quantity:1,discount:0,total:0,attributesText:"{}"};
export default function OrderItemsPage(){
 const[rows,setRows]=useState([]),[ordersList,setOrdersList]=useState([]),[productRows,setProductRows]=useState([]),[variantRows,setVariantRows]=useState([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[saving,setSaving]=useState(false);
 const canCreate=canAdmin("orderItem.create"),canUpdate=canAdmin("orderItem.update"),canDelete=canAdmin("orderItem.delete");
 const load=async()=>{setError("");const result=await Promise.allSettled([orderItems.list({page:1,limit:100}),orders.list({page:1,limit:100}),products.list({page:1,limit:100}),variants.list({page:1,limit:100})]);if(result[0].status==="fulfilled")setRows(getRows(result[0].value));else setError(result[0].reason.response?.data?.message||result[0].reason.message);if(result[1].status==="fulfilled")setOrdersList(getRows(result[1].value));if(result[2].status==="fulfilled")setProductRows(getRows(result[2].value));if(result[3].status==="fulfilled")setVariantRows(getRows(result[3].value));};
 useEffect(()=>{load()},[]);
 const showForm=row=>{setEditing(row||null);setForm(row?{...blank,...row,order:row.order?._id||row.order,product:row.product?._id||row.product,variant:row.variant?._id||row.variant,attributesText:JSON.stringify(row.attributes||{},null,2)}:{...blank});setError("");setOpen(true)};
 const save=async event=>{event.preventDefault();setSaving(true);setError("");try{const payload={...form,attributes:JSON.parse(form.attributesText||"{}"),price:Number(form.price),quantity:Number(form.quantity),discount:Number(form.discount),total:Number(form.total)};delete payload.attributesText;if(editing)await orderItems.update(editing._id,payload);else await orderItems.create(payload);setOpen(false);await load()}catch(e){setError(e instanceof SyntaxError?"Thuộc tính phải là JSON hợp lệ.":e.response?.data?.message||e.message)}finally{setSaving(false)}};
 const remove=async row=>{if(!window.confirm(`Xóa dòng “${row.productName}” khỏi đơn ${row.order?.orderNumber||"này"}? Tổng tiền đơn không tự tính lại.`))return;try{await orderItems.remove(row._id);await load()}catch(e){setError(e.response?.data?.message||e.message)}};
 const filtered=useMemo(()=>rows.filter(r=>!query||`${r.productName||""} ${r.sku||""} ${r.order?.orderNumber||""}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const setProduct=id=>{const product=productRows.find(row=>row._id===id);setForm(current=>({...current,product:id,productName:product?.name||current.productName,image:product?.thumbnail||current.image}))};
 const setVariant=id=>{const variant=variantRows.find(row=>row._id===id);setForm(current=>({...current,variant:id,variantName:variant?.name||current.variantName,sku:variant?.sku||current.sku,price:variant?.price??current.price,image:variant?.thumbnail||current.image}))};
 return <Page title="Dòng sản phẩm trong đơn" actions={<><Btn onClick={load}>↻ Làm mới</Btn>{canCreate&&<Btn className="primary" onClick={()=>showForm(null)}>+ Thêm dòng sản phẩm</Btn>}</>}>
  <div className="info-banner"><b>Đây là bản chụp sản phẩm tại thời điểm đặt hàng.</b> Thêm/sửa/xóa dòng chỉ nên dùng để sửa dữ liệu sai; hệ thống không tự tính lại tổng đơn, thanh toán hoặc tồn kho. Kiểm tra lại trang đơn hàng sau khi điều chỉnh.</div>
  <div className="toolbar"><input placeholder="Tìm sản phẩm, SKU, mã đơn…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&!open&&<div className="error">{error}</div>}
  <Table rows={filtered} columns={[{key:"order",label:"Đơn hàng",render:r=><Link className="order-code" to={`/admin/orders/${r.order?._id||r.order}`}>{r.order?.orderNumber||r.order||"—"}</Link>},{key:"productName",label:"Sản phẩm",render:r=><div><b>{r.productName}</b><small>{r.variantName||"—"}</small></div>},{key:"sku",label:"SKU",render:r=>r.sku||"—"},{key:"price",label:"Đơn giá",render:r=><Money v={r.price}/>},{key:"quantity",label:"Số lượng",render:r=><b>{r.quantity}</b>},{key:"discount",label:"Giảm",render:r=><Money v={r.discount}/>},{key:"total",label:"Thành tiền",render:r=><b><Money v={r.total}/></b>},{key:"actions",label:"Thao tác",render:r=><span className="actions">{canUpdate&&<Btn onClick={()=>showForm(r)}>Sửa</Btn>}{canDelete&&<Danger onClick={()=>remove(r)}>Xóa</Danger>}</span>}]}/>
  {open&&<Modal title={editing?"Sửa dòng sản phẩm đơn hàng":"Thêm dòng sản phẩm đơn hàng"} onClose={()=>setOpen(false)}><form className="formgrid" onSubmit={save}>{error&&<div className="error full">{error}</div>}<label>Đơn hàng<select required value={form.order} onChange={e=>setForm({...form,order:e.target.value})}><option value="">Chọn đơn hàng</option>{ordersList.map(order=><option key={order._id} value={order._id}>{order.orderNumber}</option>)}{editing?.order?._id&&!ordersList.some(order=>order._id===form.order)&&<option value={form.order}>{editing.order.orderNumber||form.order}</option>}</select></label><label>Sản phẩm<select required value={form.product} onChange={e=>setProduct(e.target.value)}><option value="">Chọn sản phẩm</option>{productRows.map(product=><option key={product._id} value={product._id}>{product.name}</option>)}{editing?.product?._id&&!productRows.some(product=>product._id===form.product)&&<option value={form.product}>{editing.product.name||form.product}</option>}</select></label><label>Variant<select required value={form.variant} onChange={e=>setVariant(e.target.value)}><option value="">Chọn Variant</option>{variantRows.map(variant=><option key={variant._id} value={variant._id}>{variant.sku||variant._id}</option>)}{editing?.variant?._id&&!variantRows.some(variant=>variant._id===form.variant)&&<option value={form.variant}>{editing.variant.sku||form.variant}</option>}</select></label><label>Tên sản phẩm lưu trong đơn<input required value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})}/></label><label>Tên Variant<input value={form.variantName} onChange={e=>setForm({...form,variantName:e.target.value})}/></label><label>SKU<input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label>Link hình ảnh<input value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></label><label>Đơn giá<input type="number" min="0" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Số lượng<input type="number" min="1" required value={form.quantity} onChange={e=>{const quantity=Number(e.target.value);setForm({...form,quantity, total:(Number(form.price)-Number(form.discount||0))*quantity})}}/></label><label>Giảm mỗi sản phẩm<input type="number" min="0" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value,total:(Number(form.price)-Number(e.target.value))*Number(form.quantity||1)})}/></label><label>Tổng dòng<input type="number" min="0" required value={form.total} onChange={e=>setForm({...form,total:e.target.value})}/></label><div className="full"><Btn type="button" onClick={()=>setOpen(false)}>Hủy</Btn> <Btn className="primary" disabled={saving}>{saving?"Đang lưu…":"Lưu dòng sản phẩm"}</Btn></div></form></Modal>}
 </Page>
}
