import React,{useEffect,useState}from"react";
import{Page,Table,Btn,Danger,Modal}from"../components/UI";
import{wishlists,users,products}from"../api";
import{canAdmin}from"../utils/adminPermissions";
const getRows=response=>{const data=response.data?.data??response.data;return Array.isArray(data)?data:data?.data||[]};
export default function WishlistsPage(){
 const[rows,setRows]=useState([]),[customers,setCustomers]=useState([]),[productRows,setProductRows]=useState([]),[error,setError]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState({user:"",products:[]}),[saving,setSaving]=useState(false);
 const canCreate=canAdmin("wishlist.create"),canUpdate=canAdmin("wishlist.update"),canDelete=canAdmin("wishlist.delete");
 const load=async()=>{setError("");const result=await Promise.allSettled([wishlists.list({page:1,limit:100}),users.list({page:1,limit:100,role:"customer"}),products.list({page:1,limit:100})]);if(result[0].status==="fulfilled")setRows(getRows(result[0].value));else setError(result[0].reason.response?.data?.message||result[0].reason.message);if(result[1].status==="fulfilled")setCustomers(getRows(result[1].value));if(result[2].status==="fulfilled")setProductRows(getRows(result[2].value));};
 useEffect(()=>{load()},[]);
 const showForm=row=>{setEditing(row||null);setForm(row?{user:row.user?._id||row.user||"",products:(row.products||[]).map(p=>p._id||p)}:{user:"",products:[]});setError("");setOpen(true)};
 const save=async event=>{event.preventDefault();setSaving(true);setError("");try{if(editing)await wishlists.update(editing._id,form);else await wishlists.create(form);setOpen(false);await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setSaving(false)}};
 const remove=async row=>{if(!window.confirm(`Xóa danh sách yêu thích của ${row.user?.name||row.user?.email||"khách hàng này"}?`))return;try{await wishlists.remove(row._id);await load()}catch(e){setError(e.response?.data?.message||e.message)}};
 return <Page title="Sản phẩm yêu thích" actions={<><Btn onClick={load}>↻ Làm mới</Btn>{canCreate&&<Btn className="primary" onClick={()=>showForm(null)}>+ Tạo danh sách</Btn>}</>}>
  <div className="info-banner"><b>Quản lý danh sách yêu thích theo tài khoản.</b> Mỗi khách chỉ có một danh sách. Chọn sản phẩm cần thêm; việc sửa danh sách sẽ cập nhật nội dung khách hàng thấy trong tài khoản.</div>{error&&!open&&<div className="error">{error}</div>}
  <Table rows={rows} columns={[{key:"user",label:"Khách hàng",render:r=><div><b>{r.user?.name||"—"}</b><small>{r.user?.email||""}</small></div>},{key:"products",label:"Sản phẩm",render:r=><div className="wishlist-products">{(r.products||[]).map(p=><span key={p._id}>{p.name||p._id}</span>)}</div>},{key:"total",label:"Số sản phẩm",render:r=><b>{(r.products||[]).length}</b>},{key:"actions",label:"Thao tác",render:r=><span className="actions">{canUpdate&&<Btn onClick={()=>showForm(r)}>Sửa</Btn>}{canDelete&&<Danger onClick={()=>remove(r)}>Xóa</Danger>}</span>}]}/>
  {open&&<Modal title={editing?"Sửa danh sách yêu thích":"Tạo danh sách yêu thích"} onClose={()=>setOpen(false)}><form className="formgrid" onSubmit={save}>{error&&<div className="error full">{error}</div>}<label className="full">Khách hàng<select required value={form.user} onChange={e=>setForm({...form,user:e.target.value})}><option value="">Chọn khách hàng</option>{customers.map(u=><option key={u._id} value={u._id}>{u.name} · {u.email}</option>)}{editing?.user?._id&&!customers.some(u=>u._id===form.user)&&<option value={form.user}>{editing.user.name||form.user}</option>}</select></label><label className="full">Sản phẩm yêu thích<select multiple size="10" value={form.products} onChange={e=>setForm({...form,products:Array.from(e.target.selectedOptions,option=>option.value)})}>{productRows.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}{editing?.products?.filter(p=>!productRows.some(row=>row._id===(p._id||p))).map(p=><option key={p._id||p} value={p._id||p}>{p.name||p._id||p}</option>)}</select><small>Giữ Ctrl (Windows) hoặc Command (Mac) để chọn nhiều sản phẩm.</small></label><div className="full"><Btn type="button" onClick={()=>setOpen(false)}>Hủy</Btn> <Btn className="primary" disabled={saving}>{saving?"Đang lưu…":"Lưu danh sách"}</Btn></div></form></Modal>}
 </Page>
}
